### ISSUE TITLE
NuGet package for uSync Content Edition

### ISSUE THREAD

**Issue by seankearney** [KevinJump/jumoo.usync#1]
We are currently using the NuGet uSync package and require a NuGet package for uSync Content Edition.

**Comment by dbardi** [comment]
I'd like to see this happen also.

**Comment by KevinJump** [comment]
I've have an experimental nuget package@ 

`Install-Package uSyncContent -Version 0.7.2`

Seems to work ok. might have to add umbraco 7 - as the dependency is on Usync 2.3.0 (u7 Version)
