### ISSUE TITLE
Umbraco 7.2 RC - Cannot sync document types

### ISSUE THREAD

**Issue by huyntvn13** [KevinJump/jumoo.usync#5]
Hi KevinJump,

I want to report an issue, which happens when I use usync with Umbraco 7.2 RC.

As you might know, a new feature in Umbraco 7.2 is Compositions (which is like Mixins).
When I create a new document type, usync writes out new def.config file, with <Compositions> section. But when I go to another computer, pull code and run, there is error (please see attached file).
![umb72_usync](https://cloud.githubusercontent.com/assets/841890/5244209/91c0c6ee-797f-11e4-8e83-db18d0422890.png)

After I deleted that section, usync worked again.

Please update usync to be compatible with this new feature.
Thank you.

**Comment by KevinJump** [comment]
are you using the jumps.umbraco.uSync.dll from the v7.2 branch? 

https://github.com/KevinJump/jumps.umbraco.usync/tree/v2.x-Umbraco7.2/Package/uSync

this isn't packaged yet (but hey umbraco 7.2 isn;t out yet) - this should work with the composite types.

**Comment by huyntvn13** [comment]
Thank you @KevinJump, I dont know about that branch. I will try those new DLLs. 
I like the new ListView features in 7.2, and cannot wait till 7.2 is out, so i'm using the RC version ;)

**Comment by huyntvn13** [comment]
Hi @KevinJump,

There are still errors in this functionality. Here is what I did:
- Delete uSync and uSync folder
- Use the new DLLs from v2.x-Umbraco7.2 branch you provided
- Run my project and uSync will create new uSync folder. Then commit it
- From another computer, I pulled code and run. The same error above appeared.

So I did some investigation by referencing your code. I found out that the error is in SyncDocType.cs > ReadFromDisk function > node.ImportContentType() line.
![usync-err-72](https://cloud.githubusercontent.com/assets/841890/5258070/76ea1e58-7a18-11e4-8f5c-56aa072ce5b6.png)

My doc types structure is like this:
--- Core Page (The dependency mentioned in above error)
------ About
------ Movies
------ Single Movie
------ ...

Movies document type allow child doctype: Single Movie, and has List View enabled.

The function above can run fine for About document type, which is also child of Core Page doc type, but not for Movies.
I think the problem is because Movies allow child doc type: Single Movie.

Can you help me out with this?

Thanks and Kind regards,

**Comment by KevinJump** [comment]
Hi

I've had a quick look, this is an issue with the core Umbraco API, if you export a document type via umbraco (right click export) - then import it via the same interface you get this error. it's how umbraco packaging service is trying to work with compositions. 

Umbraco Issue : http://issues.umbraco.org/issue/U4-5921 

I'm closing this issue - because this is the content edition repo - i'll keep an eye on it, and open one in the main usync repo if needed.

**Comment by huyntvn13** [comment]
Thank you very much. Hope that Umbraco will fix that bug soon, I really need it.
Again, much appriciate your support.
